export type PushshiftRedditPost = {
  'all_awardings': string[],
  'allow_live_comments': boolean,
  'author': string,
  'author_flair_css_class': string,
  'author_flair_richtext': string[],
  'author_flair_text': string,
  'author_flair_type': string,
  'author_fullname': string,
  'author_is_blocked': boolean,
  'author_patreon_flair': boolean,
  'author_premium': boolean,
  'body': string,
  'awarders': string[],
  'can_mod_post': boolean,
  'contest_mode': boolean,
  'created_utc': number,
  'domain': string,
  'full_link': string,
  'gildings': {},
  'id': string,
  'is_created_from_ads_ui': boolean,
  'is_crosspostable': boolean,
  'is_meta': boolean,
  'is_original_content': boolean,
  'is_reddit_media_domain': boolean,
  'is_robot_indexable': boolean,
  'is_self': boolean,
  'is_video': boolean,
  'link_flair_background_color': string
  'link_flair_css_class': string,
  'link_flair_richtext': string[],
  'link_flair_template_id': string,
  'link_flair_text': string,
  'link_flair_text_color': string,
  'link_flair_type': string,
  'locked': boolean,
  'media_only': boolean,
  'no_follow': boolean,
  'num_comments': 1,
  'num_crossposts': 0,
  'over_18': boolean,
  'parent_whitelist_status': string,
  'permalink': string,
  'pinned': boolean,
  'pwls': number,
  'removed_by_category': string,
  'retrieved_on': number,
  'score': number,
  'selftext': string,
  'send_replies': boolean,
  'spoiler': boolean,
  'stickied': boolean,
  'subreddit': string,
  'subreddit_id': 't5_2sfmf',
  'subreddit_subscribers': number,
  'subreddit_type': string,
  'suggested_sort': string,
  'thumbnail': string,
  'title': string,
  'total_awards_received': number,
  'treatment_tags': string[],
  'upvote_ratio': number,
  'url': string,
  'whitelist_status': string,
  'wls': number
}

export type PushshiftRedditCommentResponse = {
  data: PushshiftRedditPost[]
}

export type PushshiftRedditSubmissionResponse = {
  data: PushshiftRedditPost[],
}
